version: '3.8'

services:
  backend:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./apps/api/.env:/app/.env
    restart: always

  frontend:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "5176:80"
    depends_on:
      - backend
    restart: always
